# Autogenerate the vimtk.utils module
import liberator
import ubelt as ub
import re
lib = liberator.Liberator(minify=True)
lib.add_dynamic(ub.modname_to_modpath)
lib.add_dynamic(ub.modpath_to_modname)
lib.add_dynamic(ub.group_items)
lib.add_dynamic(ub.codeblock)
lib.add_dynamic(ub.indent)
lib.add_dynamic(ub.ensure_unicode)
lib.add_dynamic(ub.dict_union)
lib.add_dynamic(ub.userhome)
lib.add_dynamic(ub.shrinkuser)
lib.add_dynamic(ub.expandpath)
lib.expand(['ubelt'])
text = lib.current_sourcecode()
print(text)

vimtk_repo = ub.Path('~/code/vimtk').expand()
autogen_fpath = vimtk_repo / 'dev/autogen_utils.py'

this_text = autogen_fpath.read_text()

tsq = chr(34) * 3
nl = chr(10)
header = tsq + nl + ub.codeblock(
    f'''
    Autogen:
        # Autogenerated from ubelt (via liberator) on {ub.timestamp()}
    ''') + nl + ub.indent(this_text) + nl + tsq
text = header + nl + text

text = re.sub('  *$', '', text, flags=re.MULTILINE)
fpath = vimtk_repo / 'vimtk/util.py'
fpath.write_text(text)
